# Generated by Django 5.0.1 on 2024-10-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fecha_nacimiento',
            new_name='birth_date',
        ),
    ]
