# Generated by Django 5.0.1 on 2024-11-04 04:27

import CereScanAI.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_rename_fecha_nacimiento_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[CereScanAI.utils.valida_cedula], verbose_name='Cédula o RUC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Caracteres inválidos para un número de teléfono.', regex='^\\d{9,15}$')], verbose_name='Telefono'),
        ),
    ]
