# Generated by Django 5.0.1 on 2024-11-04 04:32

import CereScanAI.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_user_dni_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[CereScanAI.utils.valida_cedula], verbose_name='Cédula o RUC'),
        ),
    ]
