# Generated by Django 5.0.1 on 2024-11-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=80, verbose_name='Especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_medico', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resonancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flair', models.FileField(blank=True, null=True, upload_to='Resonancias/flair/')),
                ('t1ce', models.FileField(blank=True, null=True, upload_to='Resonancias/t1ce/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('informe_ia', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('tipo_anomalia', models.CharField(blank=True, max_length=200, null=True)),
                ('severidad_anomalia', models.CharField(blank=True, max_length=50, null=True)),
                ('recomendacion_medica', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonancias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('recomendaciones_adicionales', models.TextField(blank=True, null=True)),
                ('resonancia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='ScanAI.resonancia')),
            ],
        ),
        migrations.CreateModel(
            name='ResonanciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='resultados_ia/')),
                ('resonancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ScanAI.resonancia')),
            ],
        ),
    ]
